export const ADD_PROJECT: 'ADD_PROJECT' = 'ADD_PROJECT';
export const UPDATE_PROJECT: 'UPDATE_PROJECT' = 'UPDATE_PROJECT';
export const DELETE_PROJECT: 'DELETE_PROJECT' = 'DELETE_PROJECT';

export const LOAD_PROJECTS_META: 'LOAD_PROJECTS_META' = 'LOAD_PROJECTS_META';
