export const GET_USER_REQUEST: 'GET_USER_REQUEST' = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS';
export const GET_USER_FAILED: 'GET_USER_FAILED' = 'GET_USER_FAILED';

export const ADD_TODO: 'ADD_TODO' = 'ADD_TODO';
export const UPDATE_TODO: 'UPDATE_TODO' = 'UPDATE_TODO';
export const DELETE_TODO: 'DELETE_TODO' = 'DELETE_TODO';

export const ADD_SUBTODO: 'ADD_SUBTODO' = 'ADD_SUBTODO';
export const UPDATE_SUBTODO_STATUS: 'UPDATE_SUBTODO_STATUS' = 'UPDATE_SUBTODO_STATUS';
export const UPDATE_SUBTODO_TITLE: 'UPDATE_SUBTODO_TITLE' = 'UPDATE_SUBTODO_TITLE';
export const DELETE_SUBTODO: 'DELETE_SUBTODO' = 'DELETE_SUBTODO';
