export const GET_USER_REQUEST: 'GET_USER_REQUEST' = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS';
export const GET_USER_FAILED: 'GET_USER_FAILED' = 'GET_USER_FAILED';

export const ADD_TODO: 'ADD_TODO' = 'ADD_TODO';
export const UPDATE_TODO: 'UPDATE_TODO' = 'UPDATE_TODO';
export const DELETE_TODO: 'DELETE_TODO' = 'DELETE_TODO';

export const ADD_SUBTODO: 'ADD_SUBTODO' = 'ADD_SUBTODO';
export const UPDATE_SUBTODO_STATUS: 'UPDATE_SUBTODO_STATUS' = 'UPDATE_SUBTODO_STATUS';
export const UPDATE_SUBTODO_TITLE: 'UPDATE_SUBTODO_TITLE' = 'UPDATE_SUBTODO_TITLE';
export const DELETE_SUBTODO: 'DELETE_SUBTODO' = 'DELETE_SUBTODO';

export const ADD_COMMENT: 'ADD_COMMENT' = 'ADD_COMMENT';
export const UPDATE_COMMENT: 'UPDATE_COMMENT' = 'UPDATE_COMMENT';
export const DELETE_COMMENT: 'DELETE_COMMENT' = 'DELETE_COMMENT';

export const ADD_SUBCOMMENT: 'ADD_SUBCOMMENT' = 'ADD_SUBCOMMENT';
export const UPDATE_SUBCOMMENT: 'UPDATE_SUBCOMMENT' = 'UPDATE_SUBCOMMENT';
export const DELETE_SUBCOMMENT: 'DELETE_SUBCOMMENT' = 'DELETE_SUBCOMMENT';

export const CHANGE_TODO_PRIORITY: 'CHANGE_TODO_PRIORITY' = 'CHANGE_TODO_PRIORITY';
export const CHANGE_TODO_TITLE: 'CHANGE_TODO_TITLE' = 'CHANGE_TODO_TITLE';
export const CHANGE_TODO_DESCRIPTION: 'CHANGE_TODO_DESCRIPTION' = 'CHANGE_TODO_DESCRIPTION';
